### ISSUE TITLE
Size?

### ISSUE THREAD

**Issue by michalss** [hlaueriksson/GEmojiSharp#12]
Is there a way to make emoji bigger ?

**Comment by hlaueriksson** [comment]
Hi @michalss 

Are you using `GEmojiSharp.Blazor` or `GEmojiSharp.TagHelpers`?

The `g-emoji` elements has attribute `class="g-emoji"`, so you could for example use this CSS:

```css
.g-emoji {
    font-size: 25px;
}
```
